### PR TITLE
Update plugin

### PR DESCRIPTION
**Pull request by denysdovhan**
* Rewrite in JS
* Drop old Node.js support
* Update tests
* Add ESLint and use eslint-config-brunch
* Update meta data

### CODE REVIEW

**Comment by mdp** [comment]
Thanks for the update. I actually don't control this npm module on npmjs.org, I think @paulmillr does, so he'd have to be the one to update it in npm.

**Comment by paulmillr** [comment]
pushed

**Comment by denysdovhan** [comment]
That's was better to bump major version. There is breaking change. Support of Node.js <4.0 has been dropped.

**Comment by mdp** [comment]
Yeah, I missed that, should be 2.x.

Added you both to the collaborators. Also happy to move this to another maintainer, I haven't touched this code base in years.

**Pull request merged**
